# Theme Settings
theme                    : "minimal-mistakes-jekyll"
minimal_mistakes_skin    : "dark" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

# Site Settings
locale                   : "en-US"
title                    : "Stefano Beretta"
title_separator          : "|"
subtitle                 : "Senior Bioinformatician"
name                     : "Stefano Beretta"
description              : "Personal website of Stefano Beretta, Ph.D. — Senior Bioinformatician at TIGET, Milan."
url                      : "https://beretta.github.io"
baseurl                  : ""
repository               : "beretta/beretta.github.com"
teaser                   : # path of fallback teaser image
logo                     : "/assets/images/790886.jpg"
masthead_title           : # overrides the website title displayed in the masthead, use " " for no title
breadcrumbs              : false
words_per_minute         : 200
enable_copy_code_button  : false
comments:
  provider               : false
reCaptcha:
  siteKey                :
  secret                 :
atom_feed:
  path                   : # blank (default) uses feed.xml
  hide                   : # true, false (default)
search                   : true
search_full_content      : false
search_provider          : lunr

# SEO Related
google_site_verification :
bing_site_verification   :

# Social Sharing
og_image                 : "/assets/images/ProfilePhoto.jpg"
social:
  type                   : "Person"
  name                   : "Stefano Beretta"
  links:
    - "https://orcid.org/0000-0003-4375-004X"
    - "https://www.linkedin.com/in/stefano-beretta-b405131b8/"
    - "https://github.com/beretta"

# Analytics
analytics:
  provider               : false

# Site Author
author:
  name             : "Stefano Beretta"
  avatar           : "/assets/images/ProfilePhoto.jpg"
  bio              : "Senior Bioinformatician<br>TIGET — San Raffaele, Milan"
  location         : "Milan, Italy"
  email            : "ste.beretta@gmail.com"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:ste.beretta@gmail.com"
    - label: "ORCID"
      icon: "fab fa-fw fa-orcid"
      url: "https://orcid.org/0000-0003-4375-004X"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/stefano-beretta-b405131b8/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/beretta"
    - label: "Bitbucket"
      icon: "fab fa-fw fa-bitbucket"
      url: "https://bitbucket.org/bereste/"

# Site Footer
footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/beretta"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/stefano-beretta-b405131b8/"
    - label: "ORCID"
      icon: "fab fa-fw fa-orcid"
      url: "https://orcid.org/0000-0003-4375-004X"

# Reading Files
include:
  - .htaccess
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gemfile.lock
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - package-lock.json
  - Rakefile
  - README
  - tmp
keep_files:
  - .git
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed

# Outputting
permalink: /:categories/:title/
timezone: "Europe/Rome"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

# Archives
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# HTML Compression
compress_html:
  clippings: all
  ignore:
    envs: development

# Defaults
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: false
      comments: false
      share: false
      related: false
